import { StyleSheet } from "react-native";
import { fontReg, fontSemi, androidPoppinsExtras } from "../common";
import type { Theme } from "../theme";

export const createTaskItemStyles = (theme: Theme) => StyleSheet.create({
  taskItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: theme.background,
    justifyContent: "space-between",
  },
  taskItemDragging: {
    opacity: 0.6,
    backgroundColor: "#f0f7ff",
    borderRadius: 8,
  },
  gripIcon: {
    paddingHorizontal: 1,
    paddingVertical: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  taskCheckbox: {
    marginRight: 5,
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: theme.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  taskCheckboxCompleted: {
    backgroundColor: theme.primary,
  },
  checkmark: {
    color: "white",
    fontSize: 14,
    fontWeight: "bold",
  },
  taskText: {
    fontSize: 16,
    color: theme.text,
    flex: 1,
    fontFamily: fontReg,
    ...androidPoppinsExtras,
  },
  taskTextCompleted: {
    fontSize: 16,
    color: theme.textMuted,
    textDecorationLine: "line-through",
    flex: 1,
    fontFamily: fontReg,
    ...androidPoppinsExtras,
  },
  starButton: {
    padding: 4,
    marginLeft: 8,
  },
  dueDateBadge: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  dueDateText: {
    fontSize: 12,
    color: theme.success,
    marginLeft: 4,
    fontFamily: fontReg,
    ...androidPoppinsExtras,
  },
  dueDateTextOverdue: {
    color: theme.error,
  },
  dueDateTextCompleted: {
    color: theme.textMuted,
  },
  editInput: {
    flex: 1,
    fontSize: 16,
    color: theme.text,
    borderBottomWidth: 2,
    borderBottomColor: theme.primary,
    paddingVertical: 2,
    marginRight: 8,
    fontFamily: fontReg,
    ...androidPoppinsExtras,
  },
  editAction: {
    padding: 4,
    marginLeft: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.overlay,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
  },
  menuCard: {
    backgroundColor: theme.surface,
    borderRadius: 12,
    width: "100%",
    maxWidth: 320,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 10,
  },
  menuTaskPreview: {
    fontSize: 13,
    color: theme.textMuted,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
    fontStyle: "italic",
    fontFamily: fontReg,
    ...androidPoppinsExtras,
  },
  menuDivider: {
    height: 1,
    backgroundColor: theme.surfaceSecondary,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  menuIcon: {
    marginRight: 14,
    width: 20,
    textAlign: "center",
  },
  menuItemText: {
    fontSize: 15,
    color: theme.text,
    fontFamily: fontReg,
    ...androidPoppinsExtras,
  },
  menuItemDestructive: {
    color: theme.error,
  },
  menuItemCancel: {
    color: theme.textSecondary,
    fontWeight: "600",
    flex: 1,
    textAlign: "center",
    fontFamily: fontSemi,
    ...androidPoppinsExtras,
  },
});
