import { StyleSheet } from "react-native";
import type { Theme } from "../../theme";

export const createReminderModalStyles = (theme: Theme) => StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: theme.overlay,
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: theme.surface,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 34,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: theme.border,
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 16,
  },
  title: {
    fontSize: 17,
    fontWeight: "600",
    color: theme.text,
    textAlign: "center",
    marginBottom: 16,
  },
  optionsList: { maxHeight: 350 },
  option: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.surfaceSecondary,
  },
  optionSelected: { backgroundColor: "#e1f3ff" },
  optionContent: { flex: 1 },
  optionText: { fontSize: 16, color: theme.text },
  optionTextSelected: { color: theme.primary, fontWeight: "600" },
  optionDescription: { fontSize: 12, color: theme.textSecondary, marginTop: 2 },
  checkmark: { fontSize: 18, color: theme.primary },
  customPickerContainer: {
    paddingVertical: 12,
    alignItems: "center",
  },
  preview: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    backgroundColor: theme.background,
    marginHorizontal: 20,
    borderRadius: 8,
    marginTop: 16,
  },
  previewLabel: { fontSize: 14, color: theme.textSecondary, marginRight: 8 },
  previewDate: { fontSize: 14, fontWeight: "600", color: theme.primary },
  buttons: {
    flexDirection: "row",
    marginTop: 20,
    marginHorizontal: 20,
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: theme.surfaceSecondary,
    alignItems: "center",
  },
  cancelText: { fontSize: 16, fontWeight: "600", color: theme.textSecondary },
  saveButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: theme.primary,
    alignItems: "center",
  },
  saveText: { fontSize: 16, fontWeight: "600", color: "#fff" },
});
