import { StyleSheet } from "react-native";
import type { Theme } from "../../theme";

export const createRepeatModalStyles = (theme: Theme) => StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: theme.overlay,
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: theme.surface,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 34,
    maxHeight: "90%",
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: theme.border,
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 16,
  },
  title: {
    fontSize: 17,
    fontWeight: "600",
    color: theme.text,
    textAlign: "center",
    marginBottom: 16,
  },
  optionsList: { maxHeight: 500 },
  option: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.surfaceSecondary,
  },
  optionSelected: { backgroundColor: "#e1f3ff" },
  optionText: { fontSize: 16, color: theme.text },
  optionTextSelected: { color: theme.primary, fontWeight: "600" },
  timeHint: { fontSize: 14, color: theme.textSecondary },
  checkmark: { fontSize: 18, color: theme.primary },
  sectionLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 8,
    paddingHorizontal: 20,
  },
  dayPickerContainer: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.surfaceSecondary,
  },
  dayRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 12,
  },
  dayButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.surfaceSecondary,
  },
  dayButtonSelected: {
    backgroundColor: theme.primary,
  },
  dayButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: theme.text,
  },
  dayButtonTextSelected: {
    color: "#fff",
  },
  monthlyContainer: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.surfaceSecondary,
  },
  monthlyOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginHorizontal: 12,
    borderRadius: 8,
    marginBottom: 4,
  },
  monthlyOptionSelected: {
    backgroundColor: "#e1f3ff",
  },
  monthlyOptionText: {
    fontSize: 15,
    color: theme.text,
  },
  dayNumberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  dayArrow: {
    fontSize: 22,
    color: theme.primary,
    fontWeight: "600",
    paddingHorizontal: 8,
  },
  dayNumber: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.primary,
    minWidth: 24,
    textAlign: "center",
  },
  endRepeatContainer: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.surfaceSecondary,
  },
  endRepeatOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginHorizontal: 12,
    borderRadius: 8,
    marginBottom: 4,
  },
  endDatePicker: {
    paddingHorizontal: 20,
    marginTop: 8,
  },
  endDateRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 8,
  },
  endDateValue: {
    fontSize: 16,
    fontWeight: "600",
    color: theme.primary,
    minWidth: 120,
    textAlign: "center",
  },
  endDateHint: {
    fontSize: 14,
    color: theme.textSecondary,
  },
  endDateArrow: {
    padding: 4,
  },
  preview: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    backgroundColor: theme.background,
    marginHorizontal: 20,
    borderRadius: 8,
    marginTop: 16,
  },
  previewLabel: { fontSize: 14, color: theme.textSecondary, marginRight: 8 },
  previewDate: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.primary,
    textAlign: "center",
  },
  buttons: {
    flexDirection: "row",
    marginTop: 20,
    marginHorizontal: 20,
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: theme.surfaceSecondary,
    alignItems: "center",
  },
  cancelText: { fontSize: 16, fontWeight: "600", color: theme.textSecondary },
  saveButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: theme.primary,
    alignItems: "center",
  },
  saveText: { fontSize: 16, fontWeight: "600", color: "#fff" },
});
