import { StyleSheet } from "react-native";
import { fontReg, fontSemi, fontBold, androidPoppinsExtras } from "../../common";
import type { Theme } from "../../theme";

export const createProfileStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    header: {
      padding: 15,
      backgroundColor: theme.headerBackground,
      flexDirection: "row",
      alignItems: "center",
      gap: 15,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#fff",
      fontFamily: fontBold,
      ...androidPoppinsExtras,
    },
    profileSection: {
      alignItems: "center",
      paddingVertical: 20,
      backgroundColor: theme.headerBackground,
    },
    avatarContainer: {
      position: "relative",
    },
    avatar: {
      width: 100,
      height: 100,
      borderRadius: 50,
      borderWidth: 3,
      borderColor: "#fff",
    },
    avatarPlaceholder: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: theme.textMuted,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 3,
      borderColor: "#fff",
    },
    editAvatarBadge: {
      position: "absolute",
      bottom: 0,
      right: 0,
      backgroundColor: theme.primary,
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 2,
      borderColor: "#fff",
    },
    uploadingText: {
      color: "#fff",
      marginTop: 8,
      fontSize: 12,
      fontFamily: fontReg,
      ...androidPoppinsExtras,
    },
    section: {
      marginTop: 20,
      paddingHorizontal: 16,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.textSecondary,
      marginBottom: 10,
      textTransform: "uppercase",
      fontFamily: fontSemi,
      ...androidPoppinsExtras,
    },
    editNameContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.surface,
      padding: 10,
      borderRadius: 10,
      marginBottom: 10,
    },
    editNameInput: {
      flex: 1,
      fontSize: 16,
      paddingHorizontal: 8,
      color: theme.text,
      fontFamily: fontReg,
      ...androidPoppinsExtras,
    },
    saveButton: {
      padding: 8,
    },
    cancelButton: {
      padding: 8,
    },
    infoRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.surface,
      padding: 10,
      borderRadius: 10,
      marginBottom: 10,
    },
    infoText: {
      marginLeft: 12,
      flex: 1,
    },
    infoLabel: {
      fontSize: 12,
      color: theme.textSecondary,
      fontFamily: fontReg,
      ...androidPoppinsExtras,
    },
    infoValue: {
      fontSize: 16,
      color: theme.text,
      marginTop: 2,
      fontFamily: fontReg,
      ...androidPoppinsExtras,
    },
    menuItem: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.surface,
      padding: 10,
      borderRadius: 10,
      marginBottom: 10,
    },
    menuText: {
      flex: 1,
      fontSize: 16,
      color: theme.error,
      marginLeft: 12,
      fontFamily: fontReg,
      ...androidPoppinsExtras,
    },
    themeRow: {
      flexDirection: "row",
      gap: 8,
      marginBottom: 10,
    },
    themeOption: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 10,
      alignItems: "center",
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
    },
    themeOptionActive: {
      borderColor: theme.primary,
      backgroundColor: theme.surfaceSecondary,
    },
    themeOptionText: {
      fontSize: 12,
      color: theme.text,
      marginTop: 4,
      fontFamily: fontReg,
      ...androidPoppinsExtras,
    },
    themeOptionTextActive: {
      color: theme.primary,
      fontFamily: fontSemi,
    },
    footer: {
      position: "absolute",
      bottom: 30,
      left: 0,
      right: 0,
      alignItems: "center",
    },
    footerText: {
      fontSize: 12,
      color: theme.textMuted,
      fontFamily: fontReg,
      ...androidPoppinsExtras,
    },
  });
